# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the action will run. 
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Logs in to Microsoft Azure
      - name: Azure Login
        uses: Azure/login@v1                       
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: |
            az group create --location AustraliaEast --resource-group rg-githubactions
      
      - name: Deploy VNET ARM Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Override the Subscription Id set by Azure Login.
          subscriptionId: 8c6ccaa9-9f43-4f74-a91e-12a9f922d72c
          resourceGroupName: rg-githubactions
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./templates/virtualmachine.json
          parameters:
            adminPassword="x2q82a6y5BdS@s"
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: incremental
